apiVersion: v1
kind: Service
metadata:
  name: nwdaf-engine-bot-detection
  namespace: open5gs
  labels:
    app: nwdaf-engine-bot-detection
spec:
  type: ClusterIP
  selector:
    app: nwdaf-engine-bot-detection
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080