apiVersion: v1
kind: Service
metadata:
  name: nwdaf-sbi
  namespace: open5gs
  labels:
    app: nwdaf-sbi
spec:
  type: ClusterIP
  selector:
    app: nwdaf-sbi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080