apiVersion: v1
kind: Service
metadata:
  name: oai-nwdaf-database
  namespace: open5gs
  labels:
    app: oai-nwdaf-database
spec:
  type: ClusterIP
  selector:
    app: oai-nwdaf-database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017