apiVersion: v1
kind: Service
metadata:
  name: nwdaf-database
  namespace: open5gs
  labels:
    app: nwdaf-database
spec:
  type: ClusterIP
  selector:
    app: nwdaf-database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      # nodePort: 32000