apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: open5gs
data:
  kong.yml: |
    _format_version: '1.1'
    _transform: true

    services:
    - name: oai-nwdaf-nbi-analytics
      url: http://oai-nwdaf-nbi-analytics:8080/nnwdaf-analyticsinfo/v1/analytics
      routes:
        - name: oai-nwdaf-nbi-analytics-route
          hosts: 
          - oai-nwdaf-nbi-gateway
          paths: 
          - /nnwdaf-analyticsinfo/v1/analytics

    - name: oai-nwdaf-nbi-events
      url: http://nwdaf-nbi-events:8080/nnwdaf-eventssubscription/v1
      routes:
        - name: nwdaf-nbi-events-route
          hosts:
          - oai-nwdaf-nbi-gateway
          paths:
          - /nnwdaf-eventssubscription/v1

    - name: oai-nwdaf-nbi-ml
      url: http://oai-nwdaf-nbi-ml:8080/nnwdaf-mlmodelprovision/v1
      routes:
        - name: oai-nwdaf-nbi-ml-route
          hosts:
          - oai-nwdaf-nbi-gateway
          paths:
          - /nnwdaf-mlmodelprovision/v1