apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-job
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-job
  template:
    metadata:
      labels:
        app: flink-job
    spec:
      serviceAccountName: spark-sa
      containers:
      - name: flink-job
        image: fatemehshafieiardestani/flink-mongo:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        env:
        - name: MONGO_URI
          value: "mongodb://nwdaf-database.open5gs.svc.cluster.local:27017"
        - name: MONGO_DATABASE
          value: "testing"
        - name: MONGO_COLLECTION
          value: "upf"
