apiVersion: v1
kind: Service
metadata:
  name: flink-service
  namespace: open5gs
spec:
  selector:
    app: flink-job
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
