version: '3.8'

services:
  python-server:
    image: python-server
    container_name: python-server
    networks: 
      custom_net:
        ipv4_address: 192.168.60.10 
    ports:
      - "8080:8080"
networks:
  custom_net:
    driver: bridge 
    ipam:
      config:
        - subnet: 192.168.60.0/24 
      

