---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-ue5
  labels:
    app: ueransim
    component: ue
    name: ue5
spec:
  selector:
    matchLabels:
      app: ueransim
      component: ue
      name: ue5
  replicas: 1
  template:
    metadata:
      labels:
        app: ueransim
        component: ue
        name: ue5
    spec:
      initContainers:
      - name: wait-gnb
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: gnb-service:4997
        command: ["sh", "-c", "until nc -z -u $DEPENDENCIES; do echo waiting for the gNB; sleep 2; done;"]
      containers:
        - image: ghcr.io/fatemeshafiee/ueransim:v3.2.6
          imagePullPolicy: Always
          name: ue
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          # command: [ "/bin/bash", "-c", "--" ]
          # args: [ "while true; do sleep 30; done;" ]
          command: ["/ueransim/config/wrapper.sh"]
          volumeMounts:
            - mountPath: /ueransim/config
              name: ue-volume
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: ue-volume
          configMap:
            name: ue5-configmap
            items:
              - key: ue5.yaml
                path: ue5.yaml
              - key: wrapper.sh
                path: wrapper.sh
                mode: 0755
