apiVersion: v1
kind: Service
metadata:
  name: oai-nwdaf-engine
  namespace: open5gs
  labels:
    app: oai-nwdaf-engine
spec:
  type: ClusterIP
  selector:
    app: oai-nwdaf-engine
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080