apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nwdaf-nbi-events
  namespace: open5gs
  labels:
    app: oai-nwdaf-nbi-events
spec:
  selector:
    matchLabels:
      app: oai-nwdaf-nbi-events
  template:
    metadata:
      labels:
        app: oai-nwdaf-nbi-events
    spec:
      containers:
        - name: oai-nwdaf-nbi-events
          image: fatemehshafieiardestani/oai-nwdaf-nbi-events:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ENGINE_NUM_OF_UE_ROUTE
              value: /network_performance/num_of_ue
            - name: ENGINE_SESS_SUCC_RATIO_ROUTE
              value: /network_performance/sess_succ_ratio
            - name: ENGINE_UE_COMMUNICATION_ROUTE
              value: /ue_communication
            - name: ENGINE_UE_MOBILITY_ROUTE
              value: /ue_mobility
            - name: ENGINE_UNEXPECTED_LARGE_RATE_FLOW_ROUTE
              value: /abnormal_behaviour/unexpected_large_rate_flow
            - name: ENGINE_DDOS_DETECTION
              value: //abnormal_behaviour/suspicion_of_ddos_attack
            - name: ENGINE_URI
              value: http://oai-nwdaf-engine:8080
            - name: ENGINE_ADS_URI
              value: http://oai-nwdaf-engine-ads:8080
            - name: ENGINE_DDOS_URI
              value: http://nwdaf-engine-ddos:8080
            - name: SERVER_ADDR
              value: 0.0.0.0:8080 