apiVersion: v1
kind: Service
metadata:
  name: nwdaf-nbi-events
  namespace: open5gs
  labels:
    app: nwdaf-nbi-events
spec:
  type: ClusterIP
  selector:
    app: nwdaf-nbi-events
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080